version: '3.3'
services:
  redis:
    image: redis
    container_name: redisserver
    expose:
     - "6379"
    logging:
      driver: "none"
  bootredis:
    image: redis
    container_name: bootrediserver
    expose:
     - "6379"
    logging:
      driver: "none"
  bootnode:
    build: ./ghc-core
    container_name: bootnode
    ports:
      - "30314:30314"
      - "30301:30301"
      - "30301:30301/udp"
    volumes:
      - "./plasma-core:/usr/src/app"
      - "./data/logs/ghc-core:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
    links:
      - bootredis
    environment:
      REDIS_HOST: bootrediserver
      REDIS_PORT: 6379
      NODE_ENV: development
      BOOTNODE: 1
      DPT_KEY: 'd772e3d6a001a38064dd23964dd2836239fa0e6cec8b28972a87460a17210fe9'
      LOG_LEVEL: "debug"
      PRODUCTION_MODE: "OFF"
      PLASMA_CONTRACT_ADDRESS: '0x6134cf6bd676ff7abd287a02b54774de9fd2b79a'
      PLASMA_NODE_ADDRESS: '0xcDd97e8350e93eeD3224A217A42d28cF0276b67b'
      PLASMA_NODE_PRIVATE: ''
      PLASMA_NODE_PASSWORD: ''
      WEB3_HTTP_PROVIDER: ''
    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'
  mainnode:
    build: ./plasma-core
    ports:
      - "30313:30313"
      - "30302:30302"
      - "30302:30302/udp"
    volumes:
      - "./plasma-core:/usr/src/app"
      - "./data/leveldb:/var/lib/leveldb/data"
      - "./data/logs/ghc-core:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
    links: 
      - redis
      - bootnode
    environment:
      REDIS_HOST: redisserver
      REDIS_PORT: 6379
      NODE_ENV: development
      DPT_PORT: 30302
      LOG_LEVEL: "debug"
      PRODUCTION_MODE: "OFF"
      PLASMA_CONTRACT_ADDRESS: '0xd859dc3f136cb137b6bd36614c597691aa136bfa'
      PLASMA_NODE_ADDRESS: '0x2bf64b0ebd7ba3e20c54ec9f439c53e87e9d0a70'
      PLASMA_NODE_PRIVATE: 'de3385a80c15c12bc7dd7800f5d383229569269016e6501a2714a3a77885007a'
      PLASMA_NODE_PASSWORD: ''
      WEB3_HTTP_PROVIDER: ''
    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'
